version: '3.7'
services:
  # urlshortener-api
  urlshortener-api:
    image: golang:1.19
    expose:
      - "8080:8080" # gRPC
      - "8081:8081" # HTTP
    tty: true
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      APP_ENV: dev
      SERVER_PORT: 8080
      POSTGRES_USER_MASTER: test
      POSTGRES_PASSWORD_MASTER: test
      POSTGRES_HOST_MASTER: timescaledb-master
      POSTGRES_PORT_MASTER: 5432
      POSTGRES_DB_MASTER: test
      POSTGRES_USER_SLAVE: test
      POSTGRES_PASSWORD_SLAVE: test
      POSTGRES_HOST_SLAVE: timescaledb-slave
      POSTGRES_PORT_SLAVE: 5433
      POSTGRES_DB_SLAVE: test
      IS_REPLICA: true
      OTEL_AGENT: http://jaeger:14268/api/traces
      REDIS_HOST: redis:6379
    volumes:
      - ..:/app
    working_dir: /app
    command: |
      go run ./cmd/main.go
    depends_on:
      - timescaledb-master
      - timescaledb-slave
      - jaeger
      - rabbitmq
      - redis
    networks:
      - fullstack
  # urlshortener-consumer
  urlshortener-consumer:
    image: golang:1.19
    tty: true
    restart: always
    environment:
      GRPC_SERVER: urlshortener-api:8080
      RABBITMQ_HOST: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ..:/app
    working_dir: /app
    command: |
      go run ./cmd/consumer/main.go
    depends_on:
      - urlshortener-api
      - rabbitmq
    networks:
      - fullstack
  # timescaledb-master
  timescaledb-master:
    image: timescale/timescaledb:latest-pg14
    restart: always
    command: -c 'config_file=/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./primary/data:/var/lib/postgresql/data
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./primary/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - fullstack
  # timescaledb-slave
  timescaledb-slave:
    image: timescale/timescaledb:latest-pg14
    restart: always
    entrypoint: /entrypoint.sh
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./replica/data:/var/lib/postgresql/data
      - ./replica/entrypoint.sh:/entrypoint.sh
      - ./replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
    depends_on:
      - timescaledb-master
    networks:
      - fullstack
  # pgadmin
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - timescaledb-master
    networks:
      - fullstack
  # migration
  migration:
    image: migrate/migrate:v4.15.2
    restart: always
    volumes:
      - ../migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://test:test@timescaledb-master:5432/test?sslmode=disable", "up"]
    depends_on:
      - timescaledb-master
    networks:
      - fullstack
  # jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    ports:
      - "14268:14268"   # jaeger-collector HTTP server (tracer provider)
      - "16686:16686"   # HTTP server (browser UI)
    networks:
      - fullstack
  # rabbitmq
  rabbitmq:
    image: rabbitmq:3.11.8
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - fullstack
  # redis
  redis:
    image: redis:7.0.8
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - fullstack
  # schemaspy
  schemaspy:
    image: schemaspy/schemaspy:snapshot
    command: [
      "-configFile",
      "schemaspy.properties",
      "-imageformat",
      "svg"
    ]
    depends_on:
      - timescaledb-master
    volumes:
      - ./schemaspy.properties:/schemaspy.properties
      - ./schemaspy/output:/output
      - ./schemaspy/config:/config
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge
