// Code generated by MockGen. DO NOT EDIT.
// Source: url_shortener.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "github.com/yonisaka/urlshortener/api/go/grpc"
)

// GoMockURLShortenerRepo is a mock of URLShortenerRepo interface.
type GoMockURLShortenerRepo struct {
	ctrl     *gomock.Controller
	recorder *GoMockURLShortenerRepoMockRecorder
}

// GoMockURLShortenerRepoMockRecorder is the mock recorder for GoMockURLShortenerRepo.
type GoMockURLShortenerRepoMockRecorder struct {
	mock *GoMockURLShortenerRepo
}

// NewGoMockURLShortenerRepo creates a new mock instance.
func NewGoMockURLShortenerRepo(ctrl *gomock.Controller) *GoMockURLShortenerRepo {
	mock := &GoMockURLShortenerRepo{ctrl: ctrl}
	mock.recorder = &GoMockURLShortenerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockURLShortenerRepo) EXPECT() *GoMockURLShortenerRepoMockRecorder {
	return m.recorder
}

// CreateURLShortener mocks base method.
func (m *GoMockURLShortenerRepo) CreateURLShortener(ctx context.Context, params *CreateURLShortenerParams) (*grpc.URLShortener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateURLShortener", ctx, params)
	ret0, _ := ret[0].(*grpc.URLShortener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateURLShortener indicates an expected call of CreateURLShortener.
func (mr *GoMockURLShortenerRepoMockRecorder) CreateURLShortener(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateURLShortener", reflect.TypeOf((*GoMockURLShortenerRepo)(nil).CreateURLShortener), ctx, params)
}

// GetShortenedURL mocks base method.
func (m *GoMockURLShortenerRepo) GetShortenedURL(ctx context.Context, params *GetShortenedURLParams) (*grpc.URLShortener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortenedURL", ctx, params)
	ret0, _ := ret[0].(*grpc.URLShortener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortenedURL indicates an expected call of GetShortenedURL.
func (mr *GoMockURLShortenerRepoMockRecorder) GetShortenedURL(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortenedURL", reflect.TypeOf((*GoMockURLShortenerRepo)(nil).GetShortenedURL), ctx, params)
}

// ListURLShortener mocks base method.
func (m *GoMockURLShortenerRepo) ListURLShortener(ctx context.Context, params *ListURLShortenerParams) ([]*grpc.URLShortener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListURLShortener", ctx, params)
	ret0, _ := ret[0].([]*grpc.URLShortener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListURLShortener indicates an expected call of ListURLShortener.
func (mr *GoMockURLShortenerRepoMockRecorder) ListURLShortener(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListURLShortener", reflect.TypeOf((*GoMockURLShortenerRepo)(nil).ListURLShortener), ctx, params)
}
